Quote and Narration Layout Edits: Desktop
DOI-USGS/drought-timeline pull request #38
Opened 2023-08-04 21:19 UTC by aaarcher-usgs

This pull request solves a couple issues that were raised through FSP review with some new organization to the desktop version. 

One concern is how difficult it was to notice and/or pay attention to the narration box when it was across the bottom of the screen. Another concern is that because the quote text was loaded as a d3 text element *underneath* another svg layer, the links didn't work to be able to open the links in the desktop version. (note, this is a moot point in mobile because the quotes are in the bottom nav bar, which is clickable.) Also, during preliminary accessibility checks, I noticed that the d3 text wasn't getting picked up as tabable in the keyboard navigation, this also solves that problem. Finally, several people noted that the images seem randomly scattered on the timeline, rather than placed consistently.

Solution: 
Extract the quotes in desktop from the svg and add them as their own div on top of the chart. In addition, put the drought image, title, and narration text all in their own section (implemented with css flex grid). 

![image](https://github.com/DOI-USGS/drought-timeline/assets/19958841/6a45626c-dedd-4fcb-a1fc-5e5dfb888c3f)

Additional benefit: Everything is now tied to the major drought events so that the scroll triggers are simpler and the image, quote, title, red inset map highlights, and narration are all synced up. This reduced the overall complexity of several components (e.g., `droughtNarrations_desktop.js`)

2023-08-06 17:53 UTC, cnell-usgs commented
Landing view edits:
 ![image](https://github.com/DOI-USGS/drought-timeline/assets/17803537/31de8e7b-38f0-4e41-8640-aee1bcb12231)
- The arrow placement for the map here is off.
- the map would look better off the chart  on the righthand side now that you have more organization.
- "How to read the timeline" only includes some of the information on how to read the timeline, and some of it isn't within view. I like the effect of it being revealed as you scroll, but suggest moving the color legend so you see it when the page first loads
- The photo above "how to read the timeline" is visually dominant. Suggest dropping for the first load. What if that leading text were all on the right side? that would reduce the number of different pieces to see
- I really like the quote box, but think it would look better on the righthand side below the other text. That way we see more of the chart. You couldn't put the quote and the map both on the right side like I'm suggesting, but should do one. 

Text behind chart: 
<img width="1660" alt="image" src="https://github.com/DOI-USGS/drought-timeline/assets/17803537/9ac653d4-d07e-4212-bea3-882e666a2e4a">

A few other minor edits to address before merging:
- numbering in the references needs to be removed.
- change link and visited link colors. They stand out a lot and don't fit the theme of the page. Could use default colors or adjust to page style
- - text and photo alignment on right panel - make subtitle flush with image? 
<img width="493" alt="image" src="https://github.com/DOI-USGS/drought-timeline/assets/17803537/e5b048f2-4195-4c2d-89fd-e1b52ec1e1d0">

2023-08-06 18:02 UTC, cnell-usgs requested changes
Looking so much cleaner. I left a bunch of suggestions to refine it a little bit more. In general, I think you could put more in that right side panel to reduce the complexity.

2023-08-06 18:02 UTC, cnell-usgs commented on src/assets/svgs/annotation_drawings-01.svg
handwriting style for the annotations would make them feel different than the other text. There's not a ton of annotations though. It could be interesting to add more annotations down the timeline like "the longest drought observed at a gage" etc.

2023-08-08 11:39 UTC, aaarcher-usgs commented
Thanks for the review, Cee. I'll incorporate your edits except for the adding more things to the right part *until* we can hear from @hcorson-dosch-usgs with some updated screenshots. The issue is that one of the biggest reasons for the change in layout with some elements on the right, was that on Hayley's and Mandie's laptop screen, the narration text was out of space (old screenshot here):

<img width="1513" alt="image" src="https://github.com/DOI-USGS/drought-timeline/assets/19958841/3d90a38b-555b-4a37-87e6-232d72821662">

I have been designing this new layout to make sure there's enough room on the right for the longest narration, which is the Turn-of-the-Century drought. This is why the quote and inset map are on the chart, rather than on the right. *Hayley* can you pull this branch and then take a quick screenshot of the Turn of Century Drought (longest narration) and 1950s drought (long-ish quote) on your laptop screen so we can see how this is all fitting? (I can't quite mimic the size and resolution on my Mac, I can only get close)

2023-08-08 13:18 UTC, hcorson-dosch-usgs commented
Here are screenshots from my laptop screen - looks like there's quite a bit of variation in text sizing between platforms at the moment.

| Firefox      | Edge | Chrome |
| ----------- | ----------- | ----------- |
| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/cfaf5b6c-50dd-4de1-b0ad-48daa83c3445) | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/e8d3e2f0-6822-49e5-b854-f5b82dd7ae24)   | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/7ec42771-a34d-4127-91b0-3981bf5fafd6) |
| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/62c4514e-a38f-4ffe-9f16-ddc25a6659c8) | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/1cf94ec2-f23d-46c0-a29b-f14d42f6b22c)| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/f15f0f02-8977-432b-8c41-9a4ca4997df9) |
| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/8b3f4eef-b149-48de-8a86-ffb899543f7c) | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/1dc829d7-9992-4406-a267-4aba343b49cc)| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/2e8d70a2-30b9-47d5-a8a5-66b7acaf3452) |


For the initial view, I think it could look nice to have the title and first paragraph extend fully across the page, and to place the 'How to read the timeline' level with the start of the timeline:

![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/bdfbc588-54f2-4b12-8dfd-3fb68b207c2a)

 As is, the initial view remains really busy on desktop -- feels like there is too much to look at.

2023-08-15 01:04 UTC, cnell-usgs commented
Agree with Hayley on the landing view.

2023-08-15 01:05 UTC, cnell-usgs commented
I didn't realize the font sizes would be so different by browser, why is that? Is it predictable enough that we can add logic to make them the same?

2023-08-15 14:03 UTC, hcorson-dosch-usgs commented
> I didn't realize the font sizes would be so different by browser, why is that? Is it predictable enough that we can add logic to make them the same?

1. I goofed and didn't realize that my Firefox browser was zoomed out, so the difference is _not_ as stark as it appeared. I apologize for that. I've updated the screenshots, above.

2. I don't fully understand the variation from browser to browser, e.g., why Chrome text is bigger than Edge and Firefox in the updated screenshots. Browsers do have default font sizes -- the default font size in all of my browsers is 16px, which seems to be the standard. I took a quick look at our font-sizing specifications, which is a bit of mish-mash w/ holdovers from former sites of ours. In `DroughtHistory.vue` all but the `yAxisText` is set with `px` values for desktop. We're using `em` font-size values for the mobile-specific css at the moment. In `App.vue` there's a mix of `px` and `em` sizing.

### So what to do?

We could explore adding browser specific css, but I think a better first step would be to improve how we size fonts throughout the page.

I've been thinking we should try to move away from `em` b/c the sizing is pretty inconsistent. From what I understand they are relative to the parent element, so vary depending on how deep in the page structure we are:

![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/a048e946-dc46-4a3b-8053-f3366eb19c13). 

What to use to set font sizes seems historically to be a bit controversial among web developers. See [this discussion](https://stackoverflow.com/questions/11799236/should-i-use-px-or-rem-value-units-in-my-css). The _second_ recent answer from this past January makes me think we should go w/ `rem`, which is relative to the root element only. (Though there is some discussion there about using `em` instead of `rem` to determine media queries, b/c of Safari ---- right now we use `px`). [This article](https://www.freecodecamp.org/news/why-use-rem-to-set-font-size-in-css/) and [this post](https://joshcollinsworth.com/blog/never-use-px-for-font-size) (has helpful CodePens) support using `rem` - a quick scan of google search results seems like `rem` is recommended in most more recent articles/posts. It seems like the right choice for [accessibility reasons](https://www.craigabbott.co.uk/blog/accessibility-and-font-sizes/), too, so **I think we should give `rem` font sizing a go here.**

For easier `rem` scaling, it sounds like one approach is to use `%` to scale the root font size to 10px, so that you can easily map any `rem` value mentally to its pixel value (this is from [Stack Overflow](https://stackoverflow.com/questions/11799236/should-i-use-px-or-rem-value-units-in-my-css)):

> a common suggestion is to make the apparent size of rem equal to 10px. The magic number for that is 10/16 which is 0.625, or 62.5%.
> 
> :root {
>   font-size: 62.5%;
> }
> <p>If you're using the default font-size, I'm 10px tall.</p>
> 
> The problem now is that your default font-size for the rest of the page is set way too small, but there's a simple fix for that: Set a font-size on body using rem:
> 
> :root {
>   font-size: 62.5%;
> }
> 
> body {
>   font-size: 1.6rem;
> }
> <p>I'm the default font-size</p>
> 
> It's important to note, with this adjustment in place, the apparent value of rem is 10px which means any value you > might have written in px can be converted directly to rem by bumping a decimal place.
> 
> padding: 20px;
> turns into
> 
> padding: 2rem;

Of course the other complexity is that some text is added directly to the `<html>` and some is added to the `<svg>` with `D3`... I'm not sure how that plays out with sizing, and if any `<svg>` scaling settings mess w/ the css font sizing...

2023-08-15 17:47 UTC, cnell-usgs commented
I like this 10 px rem approach. It's always been an issue with different scaling when text is added directly to the svg, so that's going to need to be addressed regardless.

2023-08-16 20:24 UTC, aaarcher-usgs commented
Ok team, I think I incorporated all the above feedback. Major thanks to Hayley for sorting out the text sizing information!!

_One of the biggest changes I made, after a lot of deliberation about how to keep the focus on the data in the timeline and to reduce clutter, was to **remove the drought-specific images from the site**. This allows there to be a lot more room for text, the inset map can be on the right, and I think that the value of the photos (especially on mobile) was getting lost as it was._ 

Landing page (Firefox):

<img width="1428" alt="image" src="https://github.com/DOI-USGS/drought-timeline/assets/19958841/2fe317cb-7203-4ae5-9971-02a6c1c812cd">

Landing page (Safari):

<img width="1642" alt="image" src="https://github.com/DOI-USGS/drought-timeline/assets/19958841/49f16536-d23f-4a83-90d7-fe6364351bd0">

1970s drought (Firefox):

<img width="1421" alt="image" src="https://github.com/DOI-USGS/drought-timeline/assets/19958841/b588e1ab-9232-44a3-9900-029c26401d51">

Took regional descriptions out of here, put them as alt text 

<img width="1421" alt="image" src="https://github.com/DOI-USGS/drought-timeline/assets/19958841/e7f92849-80da-4630-a03d-4209c75218b0">

Requesting re-review from @cnell-usgs, and it might also be nice to see how this is working on small laptop from @hcorson-dosch-usgs. Although, Mandie is presenting the website to OCAP tomorrow, so getting it merged and pushed to beta before that would be great.

2023-08-16 20:30 UTC, hcorson-dosch-usgs commented
I'll pull the changes and take some screen shots. From your screenshots, the changes look great!

2023-08-16 20:58 UTC, hcorson-dosch-usgs commented
Overall I think this is a big improvement -- much cleaner, and I don't miss the images.

See screenshots and notes for a few issues.

| Firefox      | Edge | Chrome |
| ----------- | ----------- | ----------- |
| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/0228057e-4866-467b-9d9f-385eff953d09)  | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/e0e43f7f-8be0-46d3-a8e0-93bac92935f6)  | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/6e8c12e5-e901-484c-820c-126569665956) |
| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/9c53ce90-a8ea-42fd-84e5-88d4de1c18ea)  | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/f0ce4983-8e43-4a0e-87e6-c3459bfb6bc1)  | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/638ac21c-d0d7-48e3-a20d-b7610eee6ee7) |
| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/36efcb38-eed1-4c60-aa07-16aa5492c533)  | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/4f5fdcc7-5108-4656-97fe-197abc5d28f8) | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/62fabf67-861c-4c70-a64c-f09cb976c965) |
|  ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/383c540f-a1d2-49d8-8354-bdc249fb231e)  | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/825499d3-5c34-43ff-b96b-3877eabf2075) | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/dff62f65-4f57-440b-8109-b7f2e1a4e502) |
| ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/a6102769-1548-4e01-a8f4-6a6fea354e0a) | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/279eda4d-9fff-49f3-a627-e344174ff0ba) | ![image](https://github.com/DOI-USGS/drought-timeline/assets/54007288/8b5967f8-78a3-4a19-92ef-c1acfd072857) |

### Landing page
* On Edge, the drought buttons wrap to a second line
* Could we either hide the first quote until scroll, or drop it? It blocks most of the timeline from view on a laptop-sized screen

### Drought periods
* I think the main issue I see is with text sizing -- the drought descriptions go off the page for each drought. 
* The quote for each drought also needs to be a bit higher up the page, as the longer quotes get cut off.

### Regional section
* In the regional section, you might trying setting a max width for the grid, at least on laptop sizes, to bring the violin charts closer to the polar chart.

### Authors
* Could we link Scott's chart (from twitter) when it is referenced?

2023-08-16 21:02 UTC, hcorson-dosch-usgs commented
Another option for the drought descriptions at right (rather than dropping the font size) would be to split each in two and have it switch to the second part halfway through the drought

2023-08-16 21:04 UTC, hcorson-dosch-usgs commented
Also - LOVE having the map in the upper right. Feels really natural there and looks great

2023-08-16 21:46 UTC, cnell-usgs approved these changes
This looks great, let's merge it in. I think removing the photos was a good choice.

2023-08-16 22:34 UTC, aaarcher-usgs commented
> Another option for the drought descriptions at right (rather than dropping the font size) would be to split each in two and have it switch to the second part halfway through the drought

This is how I handled this issue in mobile, and I think it works well. I'll set up an issue now and incorporate that into the next version.

2023-08-16 22:34 UTC, merged